### ISSUE TITLE
IndexOutOfBoundsException al omitir argumentos de comandos

### ISSUE THREAD

**Issue by Carles-Bordas** [omarmart/E007_AnimeList#2]
Por ejemplo, la aplicación y utilizar el comando `search -anime`, de forma que se omita el nombre del anime debería producirse un error controlado por el programa en el que se indicase el problema con el comando. Sin embargo, se produce una excepción de tipo `IndexOutOfBoundsException` que se eleva hasta la raíz del programa y lo hace terminar.

**Comment by omarmart** [comment]
fixed on  b848141
