### ISSUE TITLE
Corrupción del fichero AnimeList.csv

### ISSUE THREAD

**Issue by Carles-Bordas** [omarmart/E007_AnimeList#7]
Al ejecutar el comando `change` especificando únicamente el id de un anime (por ejemplo `change 2`) el fichero AnimeList.csv queda corrupto, de forma que no se puede volver a ejecutar la aplicación.

**Comment by Carles-Bordas** [comment]
Parece que esto no se limita a utilizar el comando `change` sin argumentos, sino que al utilizarlo "bien" también se corrompe el fichero.

**Comment by omarmart** [comment]
fixed on d948fc63a57c4cd66f806a8c006d364fa104c8ee
