### ISSUE TITLE
Confirmación tras comando incorrecto

### ISSUE THREAD

**Issue by Carles-Bordas** [omarmart/E007_AnimeList#8]
Al ejecutar el comando `change` con un número de episodio incorrecto (`change 1 -progress 2500`) se indica con un mensaje que no se puede especificar un episodio mayor al número de episodios del anime pero posteriormente se indica que el cambio se ha efectuado con un mensaje `Change Successfull!`

**Comment by omarmart** [comment]
fixed on 3e5d6ee759247283b38bcfbd00dbf90d08df2956
